{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.istio.hostname }}
  gateways:
    - {{ .Release.Name }}
  http:
    - name: "{{ .Release.Name }}"
      match:
{{- $global := . }}
{{- range .Values.istio.routes }}
        - uri:
            prefix: {{ .route }}
{{- end }}
      route:
        - destination:
            host: "{{ .Release.Name }}.{{ .Values.namespace }}.svc.cluster.local"
            port:
              number: 80
{{- end }}