{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: { .Release.Name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range .Values.secrets.data }}
    {{ .key }}: {{ .value }}
{{- end }}
{{- end }}
